### ISSUE TITLE
Don't insert function signature if the following character is a parenthesis

### ISSUE THREAD

**Issue by karlek** [joefitzgerald/autocomplete-go#1]
Hi!

In sublime the autocomplete feature is aware of the following character. If the next character is a parenthesis it doesn't insert the function signature.   

![Sublime](https://cloud.githubusercontent.com/assets/1278705/11318791/c06270e4-9060-11e5-942a-62e62c2e5162.gif)

Autocomplete-go inserts the function signature every time.

![Atom](https://cloud.githubusercontent.com/assets/1278705/11318790/bddee7c6-9060-11e5-976d-d2004ad02e01.gif)

**Comment by joefitzgerald** [comment]
Yes, this makes sense. Thanks!

**Comment by spf2** [comment]
+1
<img width="722" alt="screen shot 2016-03-18 at 10 15 22 am" src="https://cloud.githubusercontent.com/assets/48122/13886069/7b571380-ecf2-11e5-9381-4e8ca87e83bc.png">

**Comment by joefitzgerald** [comment]
This is fixed in `v1.0.4`. Let me know if there are any issues with the implementation.

**Comment by spf2** [comment]
\o/
