### ISSUE TITLE
Go-config causing suggestion box on comma

### ISSUE THREAD

**Issue by nullbio** [joefitzgerald/autocomplete-go#10]
Every time I type a comma or a space or any of the characters like "!@$#%^" etc in my go files, no matter where I am in the file or what I'm typing it after it gives this suggestion window: http://imgur.com/7AeK7c0

I don't recall it always doing this, but regardless it's very frustrating. Is there any way to disable this?

Other packages I have installed (if there's some sort of weird conflict):

autocomplete-go
go-config
go-get
go-plus
environment
git-plus
jsformat
linter

If I disable go-config the problem goes away.

It would be okay if it was doing it in places that made sense, but it's unfortunately that's not the case.

Go version: 1.6.
Atom version: 1.2.4
latest version of all plugins.
Using Linux Mint 17

I also tried to add a space and a comma to the suppression box in settings but that did nothing.

Thanks :)

**Comment by nullbio** [comment]
I have a suspicion that this might be caused due to the plugin ignoring the suppression values, including the default values. I noticed there is another issue with people having a similar (or perhaps it's the same) problem. Do you have any suggestions for a work around @joefitzgerald? Your plugins are great by the way, thanks for making them, atom editor wouldn't be remotely as useful it is without these to accompany it. Cheers.

**Comment by spf2** [comment]
+1

**Comment by spf2** [comment]
I realized I had both autocomplete-go AND go-plus installed.  Once I removed autocomplete-go, the problem went away.

**Comment by joefitzgerald** [comment]
autocomplete-go will replace the functionality built-in to go-plus. I would like to find a way to reproduce this. Could you provide a sample file and list all the packages active when you experience this?

**Comment by nullbio** [comment]
@joefitzgerald  I'm not really sure the contents of the file makes a difference, it affects every file I try it in, but here's one of them anyway:

```
package main

import (
    "fmt"
    "os"

    "github.com/pobri19/sqlboiler/cmds"
)

func main() {
    // Execute SQLBoiler
    if err := cmds.SQLBoiler.Execute(); err != nil {
        fmt.Printf("Failed to execute SQLBoiler: %s", err)
        os.Exit(-1)
    }
}
```

I noticed the same thing @spf2 . I had go-plus installed without autocomplete-go and I did not have the problem. I just now  re-installed autocomplete-go, so that now I have both autocomplete-go and go-plus installed, these are the only packages I have installed in atom, and the problem appears again. 

Spaces, commas, any of these symbols "!@#$%^*)" seem to trigger it, and I suspect some other stuff I'm unaware of. The right parenthesis triggers it but not the left parenthesis "(", and neither does quotation marks.

**Comment by spf2** [comment]
Here are my active packages:

atom-jinja2@0.5.0
environment@1.1.1
go-config@1.0.0
go-get@1.0.0
go-oracle@0.2.1
go-plus@3.5.4
go-rename@0.3.0
highlight-selected@0.11.2
language-protobuf@0.5.0
language-thrift@1.0.2
tree-view-open-files@0.3.0

Previously I'd had both packages enabled. I tried enabling only autocomplete-go and the problem persisted, so it seems to be an issue with that package regardless of whether go-plus is installed.

**Comment by joefitzgerald** [comment]
@spf2 would you be open to a quick screen sharing session while you are experiencing the issue?

**Comment by spf2** [comment]
@joefitzgerald sure... how to coordinate? ...maybe pm me on twitter (same handle there)?

**Comment by spf2** [comment]
yup, fixed :)
