### ISSUE TITLE
$GOPATH Error After Latest Update

### ISSUE THREAD

**Issue by madranet** [joefitzgerald/autocomplete-go#14]
MY SETUP: MacOSX 10,11,13 / Atom V1,6,0  / autocomplete-go V1,0,4

Since updating `autocomplete-go` to 1,0,4 and the Atom editor itself to 1,6,0 within the past couple of days, I keep getting errors relating to $GOPATH not being set.  The plugin was working fine before these updates and nothing in my Go setup has changed.  

_These are the two errors I'm seeing:_
![ss 2016-03-19 at 11 24 33](https://cloud.githubusercontent.com/assets/669658/13900090/2999199e-edf6-11e5-8e0c-6ed6eaa6d480.png)

_Clicking on 'Run Go Get' produces this:_
![ss 2016-03-19 at 11 24 59](https://cloud.githubusercontent.com/assets/669658/13900092/2eb00df2-edf6-11e5-9ad8-a7ce469185cc.png)

_Atom package `terminal-plus`  confirming $GOPATH is set:_ 
![ss 2016-03-19 at 11 25 20](https://cloud.githubusercontent.com/assets/669658/13900095/34354d96-edf6-11e5-8959-c55ed712fe58.png)

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0` and ensure you are running `environment` `v1.2.0` or later.

**Comment by jbreitbart** [comment]
I have the same problem with autocomplete-go and gofmt. go-plus is version 4.1.0 and environment is 1.2.0. I am running Ubuntu. As far as I can tell $GOPATH is correct.

Is there any way for me to debug this issue?

**Comment by joefitzgerald** [comment]
Try taking a look at this: https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955. When in doubt, remember that Atom is Chromium and you can launch the developer tools: ctrl-shift-i on Linux. You can then go to console and type process.env. I suspect the comment linked above will help you resolve this.
