### ISSUE TITLE
why autocompleting inside strings?

### ISSUE THREAD

**Issue by spf2** [joefitzgerald/autocomplete-go#16]
<img width="405" alt="screen shot 2016-03-25 at 2 38 35 pm" src="https://cloud.githubusercontent.com/assets/48122/14054543/5bd0f4ea-f297-11e5-92af-cd082f9a15b1.png">

(it's hard to see, but the cursor is in the middle of the word "blue")

**Comment by joefitzgerald** [comment]
This should not be occurring. We specifically suppress autocomplete inside the `.string.quoted` scope. When you encounter situations like these, can you please ensure you check the scope(s) at the current cursor position by pressing command-option-p, and paste the resulting scopes?

**Comment by sprt** [comment]
This is what I get:
![screenshot from 2016-04-05 10-02-14](https://cloud.githubusercontent.com/assets/110295/14275200/2fd5c942-fb16-11e5-898b-ba4239ab4e98.png)

**Comment by joefitzgerald** [comment]
Please update to the latest version of the package.

**Comment by sprt** [comment]
Forgot to mention but I did. That was running v1.0.6.

**Comment by joefitzgerald** [comment]
So the scopes we block on are configurable in an option for autocomplete-go called "Scope Blacklist". Have you configured your own values here? Take a look at the default values, and then adjust them until the autocomplete dialog stops coming up. Then, let me know if the defaults should be changed.

Note that there is also a blacklist on autocomplete-plus that will suppress _all_ autocomplete providers (of which autocomplete-go is just one). Make sure you don't have any others installed that are active.

**Comment by spf2** [comment]
fwiw, i cannot repro anymore.  i had had some . includes that i've since removed, i wonder if that was causing some issues?

**Comment by sprt** [comment]
Alright so it looks like autocomplete-go's `suppressBuiltinAutocompleteProvider` setting has no effect: I tried copying autocomplete-go's default blacklist to autocomplete-plus' blacklist and the bug went away. Simply disabling autocomplete-plus' `enableBuiltinProvider` fixes it also.

**Comment by joefitzgerald** [comment]
OK, so the issue is that there is no way for a specific ac+ provider (like autocomplete-go) to prevent the built-in provider from giving suggestions. It used to be possible, but it was removed as part of the process of bundling ac+ in the core of atom.

`suppressBuiltinAutocompleteProvider` does work, but it only works if autocomplete-go says it's not blacklisted. I think this is a legitimate scenario where ac+ needs to be changed.
