### ISSUE TITLE
Autocomplete displays underneath tree view and status bar

### ISSUE THREAD

**Issue by matthewschallenkamp** [joefitzgerald/autocomplete-go#22]
![image](https://cloud.githubusercontent.com/assets/5466969/14624767/c9d5f3b2-059a-11e6-9324-b307d5c90f50.png)
As you can see in the linked image, my goquery autocomplete box is partly hidden underneath both the tree view and the status bar.

**Comment by joefitzgerald** [comment]
Please file an issue at https://github.com/atom/autocomplete-plus.
