### ISSUE TITLE
Remove parameter types

### ISSUE THREAD

**Issue by zhaokongsheng** [joefitzgerald/autocomplete-go#24]
It's quite annoying to have to delete all the parameter types after each auto completion. Is there an configuration option to remove the parameter types

**Comment by joefitzgerald** [comment]
I agree; there's an open PR for this that needs to be merged (it won't automatically merge in its current state). I got half way through it but didn't complete it. Will try and get to it in the next 48 hours.

**Comment by joefitzgerald** [comment]
This was fixed by #25 / #13. It was released in [v1.1.0](https://github.com/joefitzgerald/autocomplete-go/releases/tag/v1.1.0).
