### ISSUE TITLE
Problem with installing gocode

### ISSUE THREAD

**Issue by ghost** [joefitzgerald/autocomplete-go#28]
### Prerequisites
- [ ] Have you run `go get -u github.com/nsf/gocode` (emphasis on the `-u` flag)?
    yes
- [ ] Have you tried launching `atom .` from the terminal in your project's directory?
    yes
- [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
    yes
- [ ] Are you running the latest version of Atom? Have you tried [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable?
    yes
- [ ] Have you updated your Atom packages?
    yes
- [ ] Have you run `gocode` in server debug mode? In your terminal:
  - Run `gocode close`
       E:\src\go>gocode close
       'gocode' is not recognized as an internal or external command,
                     operable program or batch file.
  - Run `gocode -s -debug`
  - Type in atom
  - Please include some debug output from gocode
### Description

Atom complains that gocode hasn't been installed.
But I can find the stuff here: E:\src\go\src\github.com\nsf\gocode
which is in GOPATH
### Output From `go env`

set GOARCH=amd64
set GOBIN=e:\src\go\bin64
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=e:\src\go
set GORACE=
set GOROOT=e:\programs\go64
set GOTOOLDIR=e:\programs\go64\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
### Steps to Reproduce
1. start Atom
2. popup with: "The autocomplete-go package uses the gocode tool, but it cannot be found."
3. I press button "run go get"
4. next Atom start same story

Also directly in a terminal:
1. go get -u github.com/nsf/gocode
   runs without a problem
2. verified that it is installed here: E:\src\go\src\github.com\nsf\gocode
### Expected Behavior

No more complaining about getting gocode.
### Actual Behavior

Popup complaining that gocode is not yet installed.

**Comment by ghost** [comment]
Solved. Did something wrong. Thx.

**Comment by brettlangdon** [comment]
@Arie-vw do you mind sharing your resolution here? I am currently experiencing the same issue.

**Comment by alexandernst** [comment]
same here. What exactly did you do "wrong"?
