### ISSUE TITLE
Could not understand the behavior of autocomplete-go

### ISSUE THREAD

**Issue by reorx** [joefitzgerald/autocomplete-go#31]
![5](https://cloud.githubusercontent.com/assets/405972/16725653/d0e58d02-478a-11e6-872d-a3001081e3c2.gif)

Not trying to be a jerk here, but I am really confused with the behavior of autocompletion when playing with the basic functionalities. Here are three points from the above screencast:
1. When I type `import main↵`, why the `main` was interpreted as “main function”, not just the package name I want?
2. When I type `impo..`, why the suggestions stopped as if only `im` and `ims` are the trigger words? It became very useless if I have typed `imp` and going on.
3. When I expanded `func` and jumped to the function name part, why `main` is still processed as a whole `func main ..` snippet instead of just to be the function name?

I've tried to work with your rules, like when I need a main func I only type `main` and enter, or when I want to import multiple packages I type `ims` and enter, but after a while I found myself feel very uncomfortable, and I think that's not how an autocomplete plugin should work. Autocomplete should only comes when it's needed, never (or seldom) bother users to change their typing habit. I hope it could be enhanced to a better plugin, thanks for your work.

**Comment by joefitzgerald** [comment]
You are actually using autocomplete-snippets for ALL of the examples you provided above. I suspect you don't have gocode functioning correctly and so you're not seeing any other suggestions.
1. You don't import main
2. You're seeing suggestions from autocomplete-snippets based on the snippets found in the language-go package 
3. You're expanding a suggestion that is a snippet for func main

Try disabling autocomplete-snippets for a moment to figure out why you're not getting gocode suggestions. You can always tell when a suggestion is a snippet suggestion because it has a right arrow then a `|` in the left hand column.

**Comment by reorx** [comment]
Thanks for reply, that sounds reasonable, you mean there are other suggestions when type `main` after `func`? I checked my environment, and am sure gocode was installed, like when I type `fmt.`, there were plenty of suggestions shown:
![image](https://cloud.githubusercontent.com/assets/405972/16732250/d64e5fac-47ae-11e6-8051-d7c7907955b5.png)

But when I type `main` after `func`, only a snippet suggestion was shown:
![image](https://cloud.githubusercontent.com/assets/405972/16732366/62aee692-47af-11e6-99b2-4df27f40c026.png)

My key point is that in the context of `func` and `package`, `main` should not be suggested as main function snippet, if I strike tab or enter right now, the snippet expands, and it will mess up the code, so I have to strike arrow down to avoid that. If in your atom the suggestion is different, could you please show me a snapshot of how it looks like?

PS. for the 1st question, I was meant to type `package main` but failed to do so without knowing what I was typing

**Comment by joefitzgerald** [comment]
Disable autocomplete-snippets temporarily to see what I mean about those suggestions being snippets. The upside is you can create your own snippets. But this is behavior external to go-plus. Use it or don't use it at your discretion.

**Comment by reorx** [comment]
Got it, thanks, what I complained is the behavior of autocomplete-snippets & snippets package, probably not the part autocomplete-go can handle :) Closed.
