### ISSUE TITLE
Nothing showed except `PANIC` when typing [Solved]

### ISSUE THREAD

**Issue by shenwei356** [joefitzgerald/autocomplete-go#43]
### Prerequisites
- [x] Have you run `go get -u github.com/nsf/gocode` (emphasis on the `-u` flag)?
- [x] Have you tried launching `atom .` from the terminal in your project's directory?
- [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
  
  ```
  GOARCH="amd64"
  GOBIN=""
  GOEXE=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOOS="linux"
  GOPATH="/home/shenwei/shenwei/script/Go/project"
  GORACE=""
  GOROOT="/usr/local/app/go"
  GOTOOLDIR="/usr/local/app/go/pkg/tool/linux_amd64"
  CC="gcc"
  GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build730322641=/tmp/go-build -gno-record-gcc-switches"
  CXX="g++"
  CGO_ENABLED="1"
  ```
- [x] Are you running the latest version of Atom? Have you tried [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable?
  
  ```
  atom 1.9.9
  ```
- [x] Have you updated your Atom packages?
- [x] Have you run `gocode` in server debug mode? In your terminal:
  - Run `gocode close`
  - Run `gocode -s -debug`
  - Type in atom
  - Please include some debug output from gocode
  - **_It works in this step!!!**_
### Description

Nothing showed except `PANIC` when typing.

Now **_I follow this issue template, and solved it, hope people can solve this if meeting the same problem**_.
### Output From `go env`

[`go env` output here]
### Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]
### Expected Behavior

[What you expected to happen]
### Actual Behavior

[What actually happened]

**Comment by joefitzgerald** [comment]
Yeah, in general, the procedure for solving the panic issue (which will happen after _every_ go upgrade is:
1. Run `gocode close`
2. Run `go get -u github.com/nsf/gocode`

**Comment by jfesler** [comment]
This bit me as well.  Since we know the expected behavior.. is this something that can be trapped, and something useful as a popup given to the user?

In my case I blew away all of go - entirely - but did not run "gocode close".

**Comment by joefitzgerald** [comment]
That's a great idea. Offering to close and go get gocode after receiving a panic is a great way to deal with this.

**Comment by vivace-io** [comment]
**Side Note:** 

For those in the future looking to solve this issue or similar issues - make sure you've ended the gocode process after updating the `gocode` package. Otherwise, the issue will persist until you reboot your setup or `gocode` exits on it's own.

**Comment by joefitzgerald** [comment]
`gocode close` is now run automatically when you run the `golang:update-tools` command (<kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>g</kbd>&nbsp;&nbsp;<kbd>u</kbd>). Please run this first if you ever experience `PANIC` autocomplete results.
