### ISSUE TITLE
Wider Autosuggest Box

### ISSUE THREAD

**Issue by nullbio** [joefitzgerald/autocomplete-go#46]
Hi, just wondering if there is a way to make the autosuggest box wider? Quite frequently it truncates the suggestions (in particular the return values), and I find myself having to frequent the docs more often that I should need to.  This may also be a question for the Atom developers, and not you, but I'm primarily in Go land and using autocomplete-go, so I figured I'd ask here first. Just let me know if I need to redirect this elsewhere. 

Here's a screenshot of what I mean:

http://i.imgur.com/0pOKAdN.png

Thanks.

**Comment by joefitzgerald** [comment]
Closing in deference to https://github.com/atom/autocomplete-plus/issues/694.
