### ISSUE TITLE
Enable autocomplete for non imported packages

### ISSUE THREAD

**Issue by th3noname** [joefitzgerald/autocomplete-go#48]
Gocode now supports autocomplete for non imported packages.

See nsf/gocode#368

It would be nice if autocomplete-go could either activate this automatically or provide an option in the  preferences.

**Comment by joefitzgerald** [comment]
For now just run gocode set to enable this. It only has to be run once. I do plan to write something to surface the settings and allow people to toggle them.

**Comment by th3noname** [comment]
Thats what i wanted to suggest. Thank you

**Comment by zmb3** [comment]
This is fixed in 74c667830a842d525012b60d47ea69a1938b250c.

It's enabled by default but can be disabled in the package settings.
