### ISSUE TITLE
Response of automatically prompt is very slow

### ISSUE THREAD

**Issue by mohanson** [joefitzgerald/autocomplete-go#58]
It's usually have to wait more than 1 seconds to get a prompt, while almost immediately returned in Vscode.

**Comment by mohanson** [comment]
Also I use autocomplete-python in atom, it's very fast.

**Comment by joefitzgerald** [comment]
Run `gocode close && go get -u github.com/nsf/gocode`. Also, ensure you're running the latest versions of go-plus and atom. This repo is no longer used; please file future issues on the go-plus repo.
