### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by jinuthankachan** [joefitzgerald/autocomplete-go#59]
Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
<unknown> (/Users/jinu/.atom/packages/autocomplete-go/lib/gocodeprovider.js:186:39)
```

**Comment by lloiser** [comment]
> Object.dirname is deprecated 

So is this package 😉 .

This, and many other packages, have been consolidated into [`go-plus`](https://github.com/joefitzgerald/go-plus) a while ago. Please update `go-plus` to the latest version (`5.2.0`).

**Comment by jinuthankachan** [comment]
Solved with the update. Thankyou.
