### ISSUE TITLE
autocomplete-go package does not show up in Atom Editor

### ISSUE THREAD

**Issue by tukaianirban** [joefitzgerald/autocomplete-go#60]
### Prerequisites

* [x] Have you run `go get -u github.com/nsf/gocode` (emphasis on the `-u` flag)?
YES
* [x] Have you tried launching `atom .` from the terminal in your project's directory?
YES
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
YES. Included below.
* [x] Are you running the latest version of Atom? Have you tried [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable?
YES.
* [x] Have you updated your Atom packages?
YES. Please refer to stackoverflow: https://stackoverflow.com/questions/50405978/go-autocomplete-not-working-in-atom-editor

* [x] Have you run `gocode` in server debug mode? In your terminal:
  - Run `gocode close`
  - Run `gocode -s -debug`
  - Type in atom
  - Please include some debug output from gocode

### Description

[Description of the bug or feature]
I dont see "autocomplete-go" package when I search for it in "Install Packages" in Atom Editor (Windows). I am using the latest Atom Editor version 1.27.0 for Windows.

### Output From `go env`
C:\Users\emuanir>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\emuanir\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\emuanir\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessag
e-length=0 -fdebug-prefix-map=C:\Users\emuanir\AppData\Local\Temp\go-build463364
410=/tmp/go-build -gno-record-gcc-switches

[`go env` output here]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]
1. Open Settings > Install tab in Atom Editor.
2. Search for "autocomplete-go" in packages.

### Expected Behavior
The package should be available for installation.

[What you expected to happen]

### Actual Behavior

[What actually happened]
The package is not visible in the search results.

Please note that I have also reported this problem in stackoverflow: https://stackoverflow.com/questions/50405978/go-autocomplete-not-working-in-atom-editor

Thanks,

**Comment by joefitzgerald** [comment]
This package is no longer available. Please us [`go-plus`](https://atom.io/packages/go-plus) instead.
